name: datafusion

channels:
  - conda-forge

dependencies:
  - python>=3.10
  - black
  - pip
  - numpy
  - scikit-image
  - scipy
  - jupyter
  - matplotlib
  - joblib
  - tqdm
  - h5py
  - deepinv

  - pip:
      # - pyvista[jupyter]
      - torch
      - torchvision
      - torchmetrics
      - "-e ."